#!/usr/bin/env bash
#
# mainly — install, run and maintain a self-hosted instance.
#
#   ./mainly.sh start                  bring everything up (generates .env on first run)
#   ./mainly.sh user you@example.com   create a login
#
# Run it with no arguments to see everything else it does.
#
# It is deliberately chatty and deliberately refuses rather than guesses. The
# person running this is usually running it once, on a machine they care about,
# and a script that silently does the wrong thing to a database is worse than
# one that stops and says why.

set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE=.env
COMPOSE_PROJECT=mainly

# ── Output ───────────────────────────────────────────────────────────────────
# Colour only when a terminal is actually attached, so piping to a file or a
# CI log produces something readable.
if [[ -t 1 ]]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
  YELLOW=$'\033[33m'; RESET=$'\033[0m'
else
  BOLD=''; DIM=''; RED=''; GREEN=''; YELLOW=''; RESET=''
fi

say()  { printf '%s\n' "$*"; }
step() { printf '%s→%s %s\n' "$BOLD" "$RESET" "$*"; }
ok()   { printf '%s✓%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%s!%s %s\n' "$YELLOW" "$RESET" "$*" >&2; }
die()  { printf '%s✗%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

# ── Preflight ────────────────────────────────────────────────────────────────

compose() { docker compose "$@"; }

require_docker() {
  command -v docker >/dev/null 2>&1 || die \
"Docker is not installed.

  macOS / Windows   https://docs.docker.com/desktop/
  Linux             curl -fsSL https://get.docker.com | sh

Install it, start it, then run this script again."

  docker info >/dev/null 2>&1 || die \
"Docker is installed but not running. Start Docker Desktop (or 'sudo systemctl
start docker' on Linux) and run this script again."

  docker compose version >/dev/null 2>&1 || die \
"This Docker is too old — it has no 'docker compose' subcommand. Upgrade to
Docker 20.10.13 or newer, or install the compose plugin."
}

# openssl ships with macOS and every mainstream Linux, but a slim container
# image may not have it. Node is not assumed either, so fall back to /dev/urandom.
random_b64() {
  local bytes=$1
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$bytes"
  else
    head -c "$bytes" /dev/urandom | base64 | tr -d '\n'
  fi
}

# ── .env ─────────────────────────────────────────────────────────────────────

create_env() {
  step "First run — writing $ENV_FILE with freshly generated secrets"

  local secret session pgpw
  secret=$(random_b64 32)
  session=$(random_b64 32)
  # No '/', '+' or '=' — this password is interpolated into a URL.
  pgpw=$(random_b64 24 | tr -d '/+=')

  cat > "$ENV_FILE" <<EOF
# Generated by ./mainly.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC').
# Keep this file. Back up SECRET_KEY somewhere that is not this machine.

# The address you open in a browser. Change it to your real URL when you put a
# reverse proxy in front of this — cookies and CORS are checked against it, so
# it must match exactly, scheme and port included.
APP_ORIGIN=http://localhost:5274

# The port on the host. Bound to 127.0.0.1 unless BIND_ADDRESS says otherwise.
PORT=5274
BIND_ADDRESS=127.0.0.1

# ── Secrets. Generated once. Never commit this file. ────────────────────────
# SECRET_KEY encrypts stored mailbox passwords. Lose it and every account has
# to be re-added by hand. It is the one value here worth backing up.
SECRET_KEY=${secret}
SESSION_SECRET=${session}
POSTGRES_PASSWORD=${pgpw}

# ── Optional ────────────────────────────────────────────────────────────────
# Set to true only if your mail server is on a LAN, a VPN or Tailscale. It
# lets the "verify these settings" step connect to private addresses, which is
# also what makes it a request-forgery surface. Off is the safe default.
ALLOW_PRIVATE_IMAP_HOSTS=false

# Reach a mail server by private address while still validating its public
# certificate:  MAIL_HOST_OVERRIDE=mail.example.com=100.64.0.1
MAIL_HOST_OVERRIDE=

LOG_LEVEL=info
EOF

  chmod 600 "$ENV_FILE"
  ok "Wrote $ENV_FILE (mode 600)"
  say "${DIM}  Back up SECRET_KEY. Without it, stored mailbox passwords are unrecoverable.${RESET}"
  say ""
}

load_env() {
  [[ -f "$ENV_FILE" ]] || die "No $ENV_FILE. Run './mainly.sh start' first."
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}

app_url() {
  printf 'http://localhost:%s' "${PORT:-5274}"
}

# ── Commands ─────────────────────────────────────────────────────────────────

cmd_start() {
  require_docker
  [[ -f "$ENV_FILE" ]] || create_env
  load_env

  # Refuse rather than collide. A half-started stack on a taken port fails much
  # later and much more confusingly than this does.
  local port="${PORT:-5274}"
  if command -v lsof >/dev/null 2>&1 && lsof -nP -iTCP:"$port" -sTCP:LISTEN -t >/dev/null 2>&1; then
    if ! compose ps --status running --format '{{.Service}}' 2>/dev/null | grep -q '^app$'; then
      die "Port $port is already in use by something else.
Set a different PORT in $ENV_FILE, or stop whatever is holding it."
    fi
  fi

  step "Starting mainly (this pulls or builds images on the first run)"
  # Try the published image first, and fall back to building from this checkout.
  # A tag that does not exist yet — a fork, an unreleased commit, an air-gapped
  # host — should not be the difference between "it works" and a registry error.
  if [[ " $* " == *" --build "* ]] || ! compose pull --quiet app 2>/dev/null; then
    if [[ " $* " != *" --build "* ]]; then
      say "${DIM}  no published image for this version — building from source${RESET}"
      set -- "$@" --build
    fi
  fi
  compose up -d "$@"

  step "Waiting for the app to answer"
  local url; url=$(app_url)
  for _ in $(seq 1 60); do
    if curl -fsS "$url/api/health" >/dev/null 2>&1; then
      say ""
      ok "mainly is running at ${BOLD}${url}${RESET}"
      say ""
      if ! has_users; then
        say "  No login exists yet. Create one:"
        say "    ${BOLD}./mainly.sh user you@yourdomain.com${RESET}"
        say ""
      fi
      say "${DIM}  ./mainly.sh logs      follow the log${RESET}"
      say "${DIM}  ./mainly.sh stop      shut it down${RESET}"
      return 0
    fi
    sleep 2
  done

  warn "The app did not answer within two minutes. The last 40 lines of its log:"
  compose logs --tail 40 app >&2
  die "Startup failed. 'docker compose logs -f app' has the rest."
}

has_users() {
  compose exec -T db psql -U mainly -d mainly -tAc \
    'SELECT count(*) > 0 FROM users' 2>/dev/null | grep -q '^t$'
}

cmd_stop() {
  require_docker
  step "Stopping"
  compose down --remove-orphans
  ok "Stopped. Your data is still in the 'mainly_db-data' volume."
}

cmd_restart() { cmd_stop; cmd_start; }

cmd_status() {
  require_docker
  compose ps
  if [[ -f "$ENV_FILE" ]]; then
    load_env
    say ""
    if curl -fsS "$(app_url)/api/health" 2>/dev/null; then say ""; else
      warn "The app is not answering on $(app_url)"
    fi
  fi
}

cmd_logs() {
  require_docker
  compose logs -f "${1:-app}"
}

cmd_user() {
  [[ -n "${1:-}" ]] || die "usage: ./mainly.sh user <email>   (or PASSWORD=… ./mainly.sh user <email>)"
  require_docker
  step "Creating $1"
  # The password is generated and printed, or taken from $PASSWORD. Never from
  # argv, which is visible to every process on the host through `ps`.
  #
  # The env var is forwarded only when it is actually set. Passing `-e PASSWORD=`
  # would define it as the empty string, and the CLI's `??` treats "" as a value
  # — which would quietly create an account with a blank password.
  if [[ -n "${PASSWORD:-}" ]]; then
    compose exec -e PASSWORD app node dist/cli/create-user.js "$1"
  else
    compose exec app node dist/cli/create-user.js "$1"
  fi
  load_env
  say ""
  ok "Sign in at $(app_url)"
}

cmd_token() {
  require_docker
  compose exec app node dist/cli/token.js "$@"
}

cmd_update() {
  require_docker
  load_env
  step "Pulling the current image"
  compose pull app
  step "Restarting"
  # Migrations run themselves: the server awaits them before it listens.
  compose up -d app
  ok "Updated. './mainly.sh logs' to watch it come back."
}

cmd_backup() {
  require_docker
  load_env
  local dir="${1:-./backups}"
  mkdir -p "$dir"
  local file="$dir/mainly-$(date -u +%Y%m%d-%H%M%S).sql.gz"
  step "Dumping the database to $file"
  compose exec -T db pg_dump -U mainly mainly | gzip > "$file"
  ok "Wrote $file ($(du -h "$file" | cut -f1))"
  say ""
  say "${DIM}  Message metadata is a cache — your mail server still holds the mail.${RESET}"
  say "${DIM}  What this protects is accounts, preferences, saved views, labels and drafts.${RESET}"
  say "${DIM}  Back up SECRET_KEY from $ENV_FILE separately; it is not in this dump.${RESET}"
}

cmd_restore() {
  [[ -n "${1:-}" ]] || die "usage: ./mainly.sh restore <file.sql.gz>"
  [[ -f "$1" ]] || die "No such file: $1"
  require_docker
  warn "This REPLACES the current database with $1."
  read -r -p "Type 'restore' to continue: " reply
  [[ "$reply" == "restore" ]] || { say "Cancelled."; exit 0; }
  step "Restoring"
  gunzip -c "$1" | compose exec -T db psql -U mainly -d mainly
  compose restart app
  ok "Restored."
}

cmd_reset() {
  require_docker
  warn "This DELETES the database volume. Accounts, preferences and saved views go with it."
  warn "Your mail is untouched — it lives on your mail server."
  read -r -p "Type 'delete' to continue: " reply
  [[ "$reply" == "delete" ]] || { say "Cancelled."; exit 0; }
  compose down -v --remove-orphans
  ok "Gone. './mainly.sh start' begins again from empty."
}

usage() {
  cat <<EOF
${BOLD}mainly${RESET} — self-hosted multi-domain mail client

  ${BOLD}./mainly.sh start${RESET}              Start everything. Writes .env on the first run.
  ${BOLD}./mainly.sh user <email>${RESET}       Create a login. Prints a generated password.
                                 Set your own with PASSWORD=… in front of it.
  ./mainly.sh stop               Stop. Data is kept.
  ./mainly.sh restart
  ./mainly.sh status             Container state and a health check.
  ./mainly.sh logs [app|db]      Follow the log.
  ./mainly.sh update             Pull the current image and restart.
  ./mainly.sh backup [dir]       pg_dump to ./backups by default.
  ./mainly.sh restore <file>     Replace the database from a backup. Asks first.
  ./mainly.sh token <args>       Mint or revoke an API token for an agent.
  ./mainly.sh reset              Delete the database volume. Asks twice.

  ${BOLD}./mainly.sh start --build${RESET}      Build from this checkout instead of pulling.

Configuration lives in .env. Everything it accepts is in .env.example.
EOF
}

case "${1:-}" in
  start)   shift; cmd_start "$@" ;;
  stop)    cmd_stop ;;
  restart) cmd_restart ;;
  status)  cmd_status ;;
  logs)    shift; cmd_logs "$@" ;;
  user)    shift; cmd_user "$@" ;;
  token)   shift; cmd_token "$@" ;;
  update)  cmd_update ;;
  backup)  shift; cmd_backup "$@" ;;
  restore) shift; cmd_restore "$@" ;;
  reset)   cmd_reset ;;
  ''|help|-h|--help) usage ;;
  *) die "Unknown command: $1  (run './mainly.sh' for the list)" ;;
esac
